version: "3.9"

services:
  traefik:
    image: traefik:v3.6.7
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.le.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json

  dof:
    image: dof:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dof.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.dof.entrypoints=websecure"
      - "traefik.http.routers.dof.tls.certresolver=le"

  registry:
    image: registry:2
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.${HOSTNAME}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=le"
    volumes:
      - ./registry-data:/var/lib/registry
